# A generic, single database configuration.

[alembic]
# path to migration scripts
script_location = migrations

# template used to generate migration file names; during legacy
# migrations, the prefix is used as the version number
# file_template = %%(rev)s_%%(slug)s

# timezone to use when rendering the date within the migration file
# as well as the filename.
# If specified, requires the python-dateutil library.
# if left blank, localtime is used.
# timezone =

# max length of characters to use for the "slug" field
# truncate_slug_length = 40

# set to 'true' to run the environment during the 'revision' command,
# regardless of autogenerate being used or not
# revision_environment = false

# set to 'true' to allow .pyc files to be created; otherwise
# the last user of the file determines the .pyc file creation
# sourceless = false

# path separator used in compiled patterns
# (e.g. windows uses \, others use /)
# path_separator =

# version location specification; this defaults
# to migrations/versions.  When using multiple version
# directories, separate them with spaces or commas.
# version_locations = %(here)s/bar %(here)s/bat migrations/versions

# the placeholder used for the "target_metadata" attribute
# in the env.py file.
# target_metadata_target =

# set to 'true' to use the "batch mode" in migrations
# when running against SQLite.
# batch_mode = false


[post_write_hooks]
# post_write_hooks allows scripts or Python functions to be run
# after generate_revision.  See modern almebic documentation
# for examples.

[loggers]
keys = root,sqlalchemy,alembic

[handlers]
keys = console

[formatters]
keys = generic

[logger_root]
level = WARN
handlers = console
qualname =

[logger_sqlalchemy]
level = WARN
handlers =
qualname = sqlalchemy.engine

[logger_alembic]
level = INFO
handlers =
qualname = alembic

[handler_console]
class = StreamHandler
args = (sys.stderr,)
level = NOTSET
formatter = generic

[formatter_generic]
format = %(levelname)-5.5s [%(name)s] %(message)s
datefmt = %H:%M:%S
